{{- if .Values.clerk.jwks_url }}
apiVersion: v1
kind: Secret
metadata:
    name: journalist-secrets
type: Opaque
stringData:
    CLERK_JWKS_URL: {{ .Values.clerk.jwks_url | quote }}
    CLERK_SECRET_KEY: {{ .Values.clerk.secret_key | default "" | quote }}
    ALLOWED_ORIGINS: {{ .Values.cors.allowed_origins | default "" | quote }}
{{- end }}
