apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: backend
    ports:
      - port: 8001
        targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
              - name: backend
                image: journalist-backend:latest
                imagePullPolicy: Never
                ports:
                  - containerPort: 8001
                env:
                  - name: DATABASE_URL
                    value: "postgresql://postgres:devpassword@postgres:5432/journalist"
