apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    type: {{ .Values.backend.serviceType | default "ClusterIP" }}
    selector:
        app: backend
    ports:
      - port: 8001
        targetPort: 8001
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
              - name: backend
                image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
                imagePullPolicy: Always
                ports:
                  - containerPort: 8001
                envFrom:
                  - secretRef:
                      name: journalist-secrets
                  - secretRef:
                      name: postgres-credentials

