{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    selector:
        app: postgres
    ports:
      - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: postgres
spec:
    serviceName: postgres
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
              - name: postgres
                image: postgres:15-alpine
                env:
                  - name: POSTGRES_PASSWORD
                    value: "devpassword"  # LOCAL DEV ONLY - do not use in production
                  - name: POSTGRES_DB
                    value: journalist
                ports:
                  - containerPort: 5432
                volumeMounts:
                  - name: postgres-data
                    mountPath: /var/lib/postgresql/data
                    subPath: postgres
    volumeClaimTemplates:
      - metadata:
            name: postgres-data
        spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
                requests:
                    storage: 1Gi
{{- end }}