{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-csp
spec:
  headers:
    customResponseHeaders:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.clerk.accounts.dev; connect-src 'self' https://*.clerk.accounts.dev; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; frame-src https://*.clerk.accounts.dev"
{{- end }}
