apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: journalist
type: Opaque
stringData:
  CLERK_SECRET_KEY: sk_test_ULJ0vvRyjZVN72vqThdWQvGLESG2dYqnA5tcIMaCfs
  JWT_URL: https://game-goose-92.clerk.accounts.dev