backend:
  image: ghcr.io/jabril-mahamud/journalist/backend
  tag: latest
  port: 8001
  serviceType: ClusterIP

frontend:
  image: ghcr.io/jabril-mahamud/journalist/frontend
  tag: latest
  port: 3001
  serviceType: ClusterIP

ingress:
  enabled: true
  host: ""
  tls: false # set to true in values.dev.yaml and values.prod.yaml only
  clusterIssuer: false # only enable in one release to avoid conflicts

postgres:
  enabled: true
  storage: 5Gi
