backend:
  image: europe-west2-docker.pkg.dev/journalist-490612/journalist/backend
  tag: latest
  replicas: 1
  port: 8001

frontend:
  image: europe-west2-docker.pkg.dev/journalist-490612/journalist/frontend
  tag: latest
  replicas: 1
  port: 3001

postgres:
  user: postgres
  password: ""
  db: postgres
  host: db.igqnbnkvhpvdugajoltn.supabase.co
