ingress:
  host: writejrnl.uk
  tls: true

frontend:
  tag: latest

backend:
  tag: latest

cloudsql:
  enabled: true
  instanceConnectionName: "journalist-490612:europe-west2:journalist-db"

postgres:
  enabled: false
